name: ML1
channels:
  - bioconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _py-xgboost-mutex=2.0=gpu_0
  - adjusttext=1.3.0=pyhd8ed1ab_0
  - alembic=1.13.3=py311h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - aws-c-auth=0.7.20=h5f1c8d9_0
  - aws-c-cal=0.6.12=h2ba76a8_0
  - aws-c-common=0.9.17=h4ab18f5_0
  - aws-c-compression=0.2.18=h36a0aea_4
  - aws-c-event-stream=0.4.2=h161de36_10
  - aws-c-http=0.8.1=h63f54a0_13
  - aws-c-io=0.14.8=h96d4d28_0
  - aws-c-mqtt=0.10.4=hcc7299c_2
  - aws-c-s3=0.5.9=h10bd90f_0
  - aws-c-sdkutils=0.1.16=h36a0aea_0
  - aws-checksums=0.1.18=h36a0aea_4
  - aws-crt-cpp=0.26.8=h4f3a3cc_11
  - aws-sdk-cpp=1.11.267=h51dfee4_8
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bedtools=2.31.1=hf5e1c6e_2
  - blas=1.0=mkl
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bs4=4.14.2=hd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.16.0=hb05425b_5
  - catboost=1.2.3=py311h06a4308_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorlog=5.0.1=py311h06a4308_1
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.3=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.7.1=hbabe93e_0
  - gobject-introspection=1.78.1=py311h42194e9_2
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h1b29801_1
  - greenlet=3.1.1=py311h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtfparse=2.5.0=pyh7cba7a3_0
  - gtk2=2.24.33=h27e1c3a_3
  - gts=0.7.6=hb67d8dd_3
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=4.3.0=hf52aaf7_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=3.10=pyhd8ed1ab_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=py311h06a4308_1
  - ipython=8.30.0=py311h06a4308_0
  - jedi=0.19.2=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarrow=14.0.2=hefa796f_19_cpu
  - libarrow-acero=14.0.2=hbabe93e_19_cpu
  - libarrow-dataset=14.0.2=hbabe93e_19_cpu
  - libarrow-flight=14.0.2=hc4f8a93_19_cpu
  - libarrow-flight-sql=14.0.2=he4f5ca8_19_cpu
  - libarrow-gandiva=14.0.2=hc1954e9_19_cpu
  - libarrow-substrait=14.0.2=he4f5ca8_19_cpu
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgd=2.3.3=h695aa2c_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.78.4=hdc74915_0
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.23.0=h9be4e54_1
  - libgoogle-cloud-storage=2.23.0=hc7a4891_1
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - liblightgbm=4.6.0=cuda_h1f3617d_0
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=hadd5161_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libnl=3.11.0=hb9d3cd8_0
  - libparquet=14.0.2=hacf5a1f_19_cpu
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.20=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - librsvg=2.54.4=h36cc946_3
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.7=h6a678d5_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxgboost=2.1.4=cuda118_h09a87be_2
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.3=hcbfbd50_0
  - libxslt=1.1.37=h873f0b0_0
  - libzlib=1.2.13=h4ab18f5_6
  - lightgbm=4.6.0=cuda_py_0
  - llvmlite=0.42.0=py311ha6695c7_1
  - lxml=4.9.2=py311h14a6109_0
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.2.3=py311h06a4308_0
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.10.0=py311h06a4308_0
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mysql=5.7.24=h721c034_2
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.59.1=py311h96b013e_0
  - numexpr=2.10.1=py311h3c60e43_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openpyxl=3.1.5=py311h534898f_2
  - openssl=3.6.0=h26f9b46_0
  - optuna=4.6.0=pyhd8ed1ab_0
  - orc=2.0.0=h17fec99_1
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.3=py311h6a678d5_0
  - pango=1.50.7=h05da053_0
  - parso=0.8.4=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.1.0=py311hcea889d_0
  - pip=25.0=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py311h06a4308_0
  - plotly=5.24.1=py311h92b7b1e_0
  - ply=3.11=py311h06a4308_0
  - polars=0.20.31=py311h79f0488_1
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.1.4=cuda118_pyh1b5bf1a_2
  - py-xgboost-gpu=2.1.4=pyh7984362_2
  - pyarrow=14.0.2=py311hd5e4297_19_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.15.1=py311h06a4308_1
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.0=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_1
  - pyqt5-sip=12.13.0=py311h5eee18b_1
  - pysocks=1.7.1=pyha55dd90_7
  - pysradb=2.5.1=pyhdfd78af_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-graphviz=0.20.1=py311h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - qt-main=5.15.2=h7358343_9
  - rdma-core=54.0=h5888daf_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h5eee18b_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-ftp=0.3.1=pyhd8ed1ab_2
  - s2n=1.4.13=he19d79f_0
  - scikit-learn=1.6.1=py311h6a678d5_0
  - scipy=1.16.3=py311h1e13796_0
  - seaborn=0.13.2=py311h06a4308_1
  - setuptools=75.8.0=py311h06a4308_0
  - shap=0.48.0=cpu_py311h59270be_1
  - sip=6.7.12=py311h6a678d5_1
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlalchemy=2.0.37=py311h00e1ef3_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=9.0.0=py311h06a4308_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py311h5eee18b_0
  - tqdm=4.67.1=py311h92b7b1e_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing-extensions=4.12.2=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - ucx=1.15.0=ha691c75_8
  - umap-learn=0.5.9.post2=py311h38be061_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=py311h06a4308_0
  - xmltodict=0.14.2=pyhd8ed1ab_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py311h9ecbd09_2
  - zstd=1.5.5=hc292b87_0
prefix: /home/artyomt/anaconda3/envs/ML1
